ALTER TYPE "InventoryMovementType" ADD VALUE IF NOT EXISTS 'DISPENSING';
CREATE TYPE "PrescriptionStatus" AS ENUM ('DRAFT','RECEIVED','AWAITING_VERIFICATION','VERIFIED','PARTIALLY_DISPENSED','DISPENSED','CANCELLED');
CREATE TYPE "DispensingStatus" AS ENUM ('COMPLETED','VOIDED');
CREATE TABLE "Prescriber" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "organizationId" UUID NOT NULL, "name" TEXT NOT NULL, "registrationReference" TEXT, "contact" TEXT, "notes" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Prescriber_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Prescriber_organizationId_name_registrationReference_key" ON "Prescriber"("organizationId","name","registrationReference");
CREATE INDEX "Prescriber_organizationId_name_idx" ON "Prescriber"("organizationId","name");
CREATE TABLE "Prescription" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "organizationId" UUID NOT NULL, "locationId" UUID NOT NULL, "patientId" UUID NOT NULL, "prescriberId" UUID, "createdByUserId" UUID NOT NULL, "verifiedByUserId" UUID, "prescriptionNumber" VARCHAR(80) NOT NULL, "status" "PrescriptionStatus" NOT NULL DEFAULT 'DRAFT', "receivedAt" TIMESTAMP(3), "verifiedAt" TIMESTAMP(3), "cancelledAt" TIMESTAMP(3), "cancellationReason" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Prescription_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Prescription_organizationId_prescriptionNumber_key" ON "Prescription"("organizationId","prescriptionNumber");
CREATE INDEX "Prescription_organizationId_status_createdAt_idx" ON "Prescription"("organizationId","status","createdAt");
CREATE INDEX "Prescription_patientId_createdAt_idx" ON "Prescription"("patientId","createdAt");
CREATE TABLE "PrescriptionItem" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "prescriptionId" UUID NOT NULL, "productId" UUID NOT NULL, "medicineNameSnapshot" TEXT NOT NULL, "strengthSnapshot" TEXT, "prescribedQuantity" INTEGER NOT NULL, "dosageInstructions" TEXT NOT NULL, "instructionsLocale" VARCHAR(16) NOT NULL DEFAULT 'und', "repeatsAllowed" INTEGER NOT NULL DEFAULT 0, "repeatsRemaining" INTEGER NOT NULL DEFAULT 0, "notes" TEXT, CONSTRAINT "PrescriptionItem_pkey" PRIMARY KEY ("id"));
CREATE INDEX "PrescriptionItem_prescriptionId_idx" ON "PrescriptionItem"("prescriptionId");
CREATE INDEX "PrescriptionItem_productId_idx" ON "PrescriptionItem"("productId");
CREATE TABLE "DispensingRecord" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "organizationId" UUID NOT NULL, "locationId" UUID NOT NULL, "prescriptionId" UUID NOT NULL, "dispensedByUserId" UUID NOT NULL, "status" "DispensingStatus" NOT NULL DEFAULT 'COMPLETED', "notes" TEXT, "dispensedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "DispensingRecord_pkey" PRIMARY KEY ("id"));
CREATE INDEX "DispensingRecord_organizationId_dispensedAt_idx" ON "DispensingRecord"("organizationId","dispensedAt");
CREATE INDEX "DispensingRecord_prescriptionId_dispensedAt_idx" ON "DispensingRecord"("prescriptionId","dispensedAt");
CREATE TABLE "DispensingItem" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "dispensingRecordId" UUID NOT NULL, "prescriptionItemId" UUID NOT NULL, "quantity" INTEGER NOT NULL, CONSTRAINT "DispensingItem_pkey" PRIMARY KEY ("id"));
CREATE INDEX "DispensingItem_prescriptionItemId_idx" ON "DispensingItem"("prescriptionItemId");
CREATE TABLE "DispensingItemBatch" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "dispensingItemId" UUID NOT NULL, "batchId" UUID NOT NULL, "quantity" INTEGER NOT NULL, CONSTRAINT "DispensingItemBatch_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "DispensingItemBatch_dispensingItemId_batchId_key" ON "DispensingItemBatch"("dispensingItemId","batchId");
CREATE INDEX "DispensingItemBatch_batchId_idx" ON "DispensingItemBatch"("batchId");
ALTER TABLE "Prescriber" ADD CONSTRAINT "Prescriber_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Prescription" ADD CONSTRAINT "Prescription_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Prescription" ADD CONSTRAINT "Prescription_locationId_fkey" FOREIGN KEY ("locationId") REFERENCES "Location"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Prescription" ADD CONSTRAINT "Prescription_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Prescription" ADD CONSTRAINT "Prescription_prescriberId_fkey" FOREIGN KEY ("prescriberId") REFERENCES "Prescriber"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Prescription" ADD CONSTRAINT "Prescription_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Prescription" ADD CONSTRAINT "Prescription_verifiedByUserId_fkey" FOREIGN KEY ("verifiedByUserId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PrescriptionItem" ADD CONSTRAINT "PrescriptionItem_prescriptionId_fkey" FOREIGN KEY ("prescriptionId") REFERENCES "Prescription"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PrescriptionItem" ADD CONSTRAINT "PrescriptionItem_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "DispensingRecord" ADD CONSTRAINT "DispensingRecord_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "DispensingRecord" ADD CONSTRAINT "DispensingRecord_locationId_fkey" FOREIGN KEY ("locationId") REFERENCES "Location"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "DispensingRecord" ADD CONSTRAINT "DispensingRecord_prescriptionId_fkey" FOREIGN KEY ("prescriptionId") REFERENCES "Prescription"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "DispensingRecord" ADD CONSTRAINT "DispensingRecord_dispensedByUserId_fkey" FOREIGN KEY ("dispensedByUserId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "DispensingItem" ADD CONSTRAINT "DispensingItem_dispensingRecordId_fkey" FOREIGN KEY ("dispensingRecordId") REFERENCES "DispensingRecord"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "DispensingItem" ADD CONSTRAINT "DispensingItem_prescriptionItemId_fkey" FOREIGN KEY ("prescriptionItemId") REFERENCES "PrescriptionItem"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "DispensingItemBatch" ADD CONSTRAINT "DispensingItemBatch_dispensingItemId_fkey" FOREIGN KEY ("dispensingItemId") REFERENCES "DispensingItem"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "DispensingItemBatch" ADD CONSTRAINT "DispensingItemBatch_batchId_fkey" FOREIGN KEY ("batchId") REFERENCES "Batch"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PrescriptionItem" ADD CONSTRAINT "PrescriptionItem_quantity_check" CHECK ("prescribedQuantity" > 0 AND "repeatsAllowed" >= 0 AND "repeatsRemaining" >= 0 AND "repeatsRemaining" <= "repeatsAllowed");
ALTER TABLE "DispensingItem" ADD CONSTRAINT "DispensingItem_quantity_check" CHECK ("quantity" > 0);
ALTER TABLE "DispensingItemBatch" ADD CONSTRAINT "DispensingItemBatch_quantity_check" CHECK ("quantity" > 0);
INSERT INTO "Permission" ("id","code","description") VALUES (gen_random_uuid(),'prescriptions:read','Read prescriptions'),(gen_random_uuid(),'prescriptions:create','Create prescriptions'),(gen_random_uuid(),'prescriptions:update','Update prescription status'),(gen_random_uuid(),'prescriptions:verify','Verify prescriptions'),(gen_random_uuid(),'dispensing:read','Read dispensing history'),(gen_random_uuid(),'dispensing:create','Dispense verified prescriptions') ON CONFLICT ("code") DO NOTHING;
INSERT INTO "RolePermission" ("roleId","permissionId") SELECT r."id",p."id" FROM "Role" r CROSS JOIN "Permission" p WHERE r."name" IN ('administrator','pharmacist') AND p."code" IN ('prescriptions:read','prescriptions:create','prescriptions:update','prescriptions:verify','dispensing:read','dispensing:create') ON CONFLICT DO NOTHING;
INSERT INTO "RolePermission" ("roleId","permissionId") SELECT r."id",p."id" FROM "Role" r CROSS JOIN "Permission" p WHERE r."name" IN ('pharmacy-technician','cashier') AND p."code" IN ('prescriptions:read','dispensing:read') ON CONFLICT DO NOTHING;
